# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b540843e98c34a2c74ae7d683b9759a50c1155008ba68c4d847beca98ebc022bdccd76c9a827587f58a7ab70c87408fd38d3dab9c980362e3d90afadf07d936e

test:
  secret_key_base: b67374dfd4699e965c1b1aaa0caed065219b30bf984966c34ac298dcfd4b0fab5199a61c1400d4ebfd4d2fa0d5aafbab64c4621cecec537ac270af124fadb426

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  google_analytics_code: YOUR CODE HERE
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>